services:
  db:
    image: mariadb:10.11
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    volumes:
      - db_data:/var/lib/mysql
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]

  web:
    image: prestashop/prestashop:8.2.3-apache
    depends_on:
      - db
    ports:
      - "${WEB_PORT}:80"
    environment:
      DB_SERVER: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWD: ${DB_PASS}

      PS_INSTALL_AUTO: 1
      PS_DEV_MODE: 1
      PS_DOMAIN: "${DOMAIN}:${WEB_PORT}"

      ADMIN_MAIL: admin@local.test
      ADMIN_PASSWD: admin12345

      PS_LANGUAGE: pl
      PS_COUNTRY: PL
      PS_ENABLE_SSL: 0

      # kluczowe: nie kasuj DB w trakcie auto-install
      PS_ERASE_DB: 0
    entrypoint: ["/docker-entrypoint-prestashop.sh"]
    command: ["apache2-foreground"]
    volumes:
      - ./prestashop:/var/www/html
      - ./scripts/docker-entrypoint-prestashop.sh:/docker-entrypoint-prestashop.sh:ro

  pma:
    image: phpmyadmin:latest
    depends_on:
      - db
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: db

volumes:
  db_data:
